pull_request_title: 'fix: new Crowdin updates'
commit_message: 'fix: new translations %original_file_name% from Crowdin'
files:
  - source: /src/assets/locales/en
    translation: /src/assets/locales/%locale%/translation.json
