// @generated by protoc-gen-es v1.4.1 with parameter "target=ts,import_extension=.ts"
// @generated from file plugnmeet_analytics.proto (package plugnmeet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf';
import { Message, proto3, protoInt64 } from '@bufbuild/protobuf';

/**
 * @generated from enum plugnmeet.AnalyticsEventType
 */
export enum AnalyticsEventType {
  /**
   * @generated from enum value: ANALYTICS_EVENT_TYPE_ROOM = 0;
   */
  ROOM = 0,

  /**
   * @generated from enum value: ANALYTICS_EVENT_TYPE_USER = 1;
   */
  USER = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(AnalyticsEventType)
proto3.util.setEnumType(AnalyticsEventType, 'plugnmeet.AnalyticsEventType', [
  { no: 0, name: 'ANALYTICS_EVENT_TYPE_ROOM' },
  { no: 1, name: 'ANALYTICS_EVENT_TYPE_USER' },
]);

/**
 * @generated from enum plugnmeet.AnalyticsEvents
 */
export enum AnalyticsEvents {
  /**
   * @generated from enum value: ANALYTICS_EVENT_UNKNOWN = 0;
   */
  ANALYTICS_EVENT_UNKNOWN = 0,

  /**
   * room related
   *
   * @generated from enum value: ANALYTICS_EVENT_ROOM_POLL_ADDED = 1;
   */
  ANALYTICS_EVENT_ROOM_POLL_ADDED = 1,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_POLL_ENDED = 2;
   */
  ANALYTICS_EVENT_ROOM_POLL_ENDED = 2,

  /**
   * user join will be room related
   * after take record it will pass to user
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_JOINED = 3;
   */
  ANALYTICS_EVENT_USER_JOINED = 3,

  /**
   * room recorder
   *
   * @generated from enum value: ANALYTICS_EVENT_ROOM_RECORDING_STATUS = 4;
   */
  ANALYTICS_EVENT_ROOM_RECORDING_STATUS = 4,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_RTMP_STATUS = 5;
   */
  ANALYTICS_EVENT_ROOM_RTMP_STATUS = 5,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_BREAKOUT_ROOM = 6;
   */
  ANALYTICS_EVENT_ROOM_BREAKOUT_ROOM = 6,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_ETHERPAD_STATUS = 7;
   */
  ANALYTICS_EVENT_ROOM_ETHERPAD_STATUS = 7,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_EXTERNAL_DISPLAY_LINK_STATUS = 8;
   */
  ANALYTICS_EVENT_ROOM_EXTERNAL_DISPLAY_LINK_STATUS = 8,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_EXTERNAL_MEDIA_PLAYER_STATUS = 9;
   */
  ANALYTICS_EVENT_ROOM_EXTERNAL_MEDIA_PLAYER_STATUS = 9,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_STATUS = 10;
   */
  ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_STATUS = 10,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_TOTAL_USAGE = 11;
   */
  ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_TOTAL_USAGE = 11,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_INGRESS_CREATED = 12;
   */
  ANALYTICS_EVENT_ROOM_INGRESS_CREATED = 12,

  /**
   * @generated from enum value: ANALYTICS_EVENT_ROOM_WHITEBOARD_FILES = 13;
   */
  ANALYTICS_EVENT_ROOM_WHITEBOARD_FILES = 13,

  /**
   * here all related with user
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_LEFT = 14;
   */
  ANALYTICS_EVENT_USER_LEFT = 14,

  /**
   * microphone
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_MIC_STATUS = 15;
   */
  ANALYTICS_EVENT_USER_MIC_STATUS = 15,

  /**
   * @generated from enum value: ANALYTICS_EVENT_USER_TALKED = 16;
   */
  ANALYTICS_EVENT_USER_TALKED = 16,

  /**
   * in milliseconds
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_TALKED_DURATION = 17;
   */
  ANALYTICS_EVENT_USER_TALKED_DURATION = 17,

  /**
   * webcam
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_WEBCAM_STATUS = 18;
   */
  ANALYTICS_EVENT_USER_WEBCAM_STATUS = 18,

  /**
   * screen share
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_SCREEN_SHARE_STATUS = 19;
   */
  ANALYTICS_EVENT_USER_SCREEN_SHARE_STATUS = 19,

  /**
   * polls
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_VOTED_POLL = 20;
   */
  ANALYTICS_EVENT_USER_VOTED_POLL = 20,

  /**
   * chat
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_PUBLIC_CHAT = 21;
   */
  ANALYTICS_EVENT_USER_PUBLIC_CHAT = 21,

  /**
   * @generated from enum value: ANALYTICS_EVENT_USER_PRIVATE_CHAT = 22;
   */
  ANALYTICS_EVENT_USER_PRIVATE_CHAT = 22,

  /**
   * @generated from enum value: ANALYTICS_EVENT_USER_CHAT_FILES = 23;
   */
  ANALYTICS_EVENT_USER_CHAT_FILES = 23,

  /**
   * whiteboard
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_WHITEBOARD_ANNOTATED = 24;
   */
  ANALYTICS_EVENT_USER_WHITEBOARD_ANNOTATED = 24,

  /**
   * @generated from enum value: ANALYTICS_EVENT_USER_WHITEBOARD_FILES = 25;
   */
  ANALYTICS_EVENT_USER_WHITEBOARD_FILES = 25,

  /**
   * speech services
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_SPEECH_SERVICES_USAGE = 26;
   */
  ANALYTICS_EVENT_USER_SPEECH_SERVICES_USAGE = 26,

  /**
   * @generated from enum value: ANALYTICS_EVENT_USER_SPEECH_SERVICES_STATUS = 27;
   */
  ANALYTICS_EVENT_USER_SPEECH_SERVICES_STATUS = 27,

  /**
   * etc
   *
   * @generated from enum value: ANALYTICS_EVENT_USER_INTERFACE_VISIBILITY = 28;
   */
  ANALYTICS_EVENT_USER_INTERFACE_VISIBILITY = 28,

  /**
   * @generated from enum value: ANALYTICS_EVENT_USER_RAISE_HAND = 29;
   */
  ANALYTICS_EVENT_USER_RAISE_HAND = 29,

  /**
   * @generated from enum value: ANALYTICS_EVENT_USER_CONNECTION_QUALITY = 30;
   */
  ANALYTICS_EVENT_USER_CONNECTION_QUALITY = 30,
}
// Retrieve enum metadata with: proto3.getEnumType(AnalyticsEvents)
proto3.util.setEnumType(AnalyticsEvents, 'plugnmeet.AnalyticsEvents', [
  { no: 0, name: 'ANALYTICS_EVENT_UNKNOWN' },
  { no: 1, name: 'ANALYTICS_EVENT_ROOM_POLL_ADDED' },
  { no: 2, name: 'ANALYTICS_EVENT_ROOM_POLL_ENDED' },
  { no: 3, name: 'ANALYTICS_EVENT_USER_JOINED' },
  { no: 4, name: 'ANALYTICS_EVENT_ROOM_RECORDING_STATUS' },
  { no: 5, name: 'ANALYTICS_EVENT_ROOM_RTMP_STATUS' },
  { no: 6, name: 'ANALYTICS_EVENT_ROOM_BREAKOUT_ROOM' },
  { no: 7, name: 'ANALYTICS_EVENT_ROOM_ETHERPAD_STATUS' },
  { no: 8, name: 'ANALYTICS_EVENT_ROOM_EXTERNAL_DISPLAY_LINK_STATUS' },
  { no: 9, name: 'ANALYTICS_EVENT_ROOM_EXTERNAL_MEDIA_PLAYER_STATUS' },
  { no: 10, name: 'ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_STATUS' },
  { no: 11, name: 'ANALYTICS_EVENT_ROOM_SPEECH_SERVICE_TOTAL_USAGE' },
  { no: 12, name: 'ANALYTICS_EVENT_ROOM_INGRESS_CREATED' },
  { no: 13, name: 'ANALYTICS_EVENT_ROOM_WHITEBOARD_FILES' },
  { no: 14, name: 'ANALYTICS_EVENT_USER_LEFT' },
  { no: 15, name: 'ANALYTICS_EVENT_USER_MIC_STATUS' },
  { no: 16, name: 'ANALYTICS_EVENT_USER_TALKED' },
  { no: 17, name: 'ANALYTICS_EVENT_USER_TALKED_DURATION' },
  { no: 18, name: 'ANALYTICS_EVENT_USER_WEBCAM_STATUS' },
  { no: 19, name: 'ANALYTICS_EVENT_USER_SCREEN_SHARE_STATUS' },
  { no: 20, name: 'ANALYTICS_EVENT_USER_VOTED_POLL' },
  { no: 21, name: 'ANALYTICS_EVENT_USER_PUBLIC_CHAT' },
  { no: 22, name: 'ANALYTICS_EVENT_USER_PRIVATE_CHAT' },
  { no: 23, name: 'ANALYTICS_EVENT_USER_CHAT_FILES' },
  { no: 24, name: 'ANALYTICS_EVENT_USER_WHITEBOARD_ANNOTATED' },
  { no: 25, name: 'ANALYTICS_EVENT_USER_WHITEBOARD_FILES' },
  { no: 26, name: 'ANALYTICS_EVENT_USER_SPEECH_SERVICES_USAGE' },
  { no: 27, name: 'ANALYTICS_EVENT_USER_SPEECH_SERVICES_STATUS' },
  { no: 28, name: 'ANALYTICS_EVENT_USER_INTERFACE_VISIBILITY' },
  { no: 29, name: 'ANALYTICS_EVENT_USER_RAISE_HAND' },
  { no: 30, name: 'ANALYTICS_EVENT_USER_CONNECTION_QUALITY' },
]);

/**
 * @generated from enum plugnmeet.AnalyticsStatus
 */
export enum AnalyticsStatus {
  /**
   * @generated from enum value: ANALYTICS_STATUS_STARTED = 0;
   */
  STARTED = 0,

  /**
   * @generated from enum value: ANALYTICS_STATUS_ENDED = 1;
   */
  ENDED = 1,

  /**
   * @generated from enum value: ANALYTICS_STATUS_MUTED = 2;
   */
  MUTED = 2,

  /**
   * @generated from enum value: ANALYTICS_STATUS_UNMUTED = 3;
   */
  UNMUTED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(AnalyticsStatus)
proto3.util.setEnumType(AnalyticsStatus, 'plugnmeet.AnalyticsStatus', [
  { no: 0, name: 'ANALYTICS_STATUS_STARTED' },
  { no: 1, name: 'ANALYTICS_STATUS_ENDED' },
  { no: 2, name: 'ANALYTICS_STATUS_MUTED' },
  { no: 3, name: 'ANALYTICS_STATUS_UNMUTED' },
]);

/**
 * @generated from message plugnmeet.AnalyticsDataMsg
 */
export class AnalyticsDataMsg extends Message<AnalyticsDataMsg> {
  /**
   * @generated from field: plugnmeet.AnalyticsEventType event_type = 1;
   */
  eventType = AnalyticsEventType.ROOM;

  /**
   * @generated from field: plugnmeet.AnalyticsEvents event_name = 2;
   */
  eventName = AnalyticsEvents.ANALYTICS_EVENT_UNKNOWN;

  /**
   * @generated from field: string room_id = 3;
   */
  roomId = '';

  /**
   * should be unix milliseconds
   *
   * @generated from field: int64 time = 4;
   */
  time = protoInt64.zero;

  /**
   * if we pass value here then it will use redis SET to set the value for the key
   *
   * @generated from field: optional string event_value_string = 5;
   */
  eventValueString?: string;

  /**
   * if we pass value here then it will use redis INCRBY to increment value for the key
   *
   * @generated from field: optional int64 event_value_integer = 6;
   */
  eventValueInteger?: bigint;

  /**
   * if we pass value here then it will use redis HSET to set hash field value for the key
   * hash field will be unix milliseconds, so it will remain unique as always
   *
   * @generated from field: optional string hset_value = 7;
   */
  hsetValue?: string;

  /**
   * @generated from field: optional string room_sid = 8;
   */
  roomSid?: string;

  /**
   * @generated from field: optional string user_id = 9;
   */
  userId?: string;

  /**
   * @generated from field: optional string user_name = 10;
   */
  userName?: string;

  /**
   * this extra_data can be use for various purposes like, room or user metadata
   *
   * @generated from field: optional string extra_data = 11;
   */
  extraData?: string;

  constructor(data?: PartialMessage<AnalyticsDataMsg>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'plugnmeet.AnalyticsDataMsg';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'event_type',
      kind: 'enum',
      T: proto3.getEnumType(AnalyticsEventType),
    },
    {
      no: 2,
      name: 'event_name',
      kind: 'enum',
      T: proto3.getEnumType(AnalyticsEvents),
    },
    { no: 3, name: 'room_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 4, name: 'time', kind: 'scalar', T: 3 /* ScalarType.INT64 */ },
    {
      no: 5,
      name: 'event_value_string',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 6,
      name: 'event_value_integer',
      kind: 'scalar',
      T: 3 /* ScalarType.INT64 */,
      opt: true,
    },
    {
      no: 7,
      name: 'hset_value',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 8,
      name: 'room_sid',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 9,
      name: 'user_id',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 10,
      name: 'user_name',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 11,
      name: 'extra_data',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): AnalyticsDataMsg {
    return new AnalyticsDataMsg().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsDataMsg {
    return new AnalyticsDataMsg().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsDataMsg {
    return new AnalyticsDataMsg().fromJsonString(jsonString, options);
  }

  static equals(
    a: AnalyticsDataMsg | PlainMessage<AnalyticsDataMsg> | undefined,
    b: AnalyticsDataMsg | PlainMessage<AnalyticsDataMsg> | undefined,
  ): boolean {
    return proto3.util.equals(AnalyticsDataMsg, a, b);
  }
}

/**
 * @generated from message plugnmeet.AnalyticsEventValue
 */
export class AnalyticsEventValue extends Message<AnalyticsEventValue> {
  /**
   * @generated from field: int64 time = 1;
   */
  time = protoInt64.zero;

  /**
   * @generated from field: string value = 2;
   */
  value = '';

  constructor(data?: PartialMessage<AnalyticsEventValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'plugnmeet.AnalyticsEventValue';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'time', kind: 'scalar', T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: 'value', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): AnalyticsEventValue {
    return new AnalyticsEventValue().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsEventValue {
    return new AnalyticsEventValue().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsEventValue {
    return new AnalyticsEventValue().fromJsonString(jsonString, options);
  }

  static equals(
    a: AnalyticsEventValue | PlainMessage<AnalyticsEventValue> | undefined,
    b: AnalyticsEventValue | PlainMessage<AnalyticsEventValue> | undefined,
  ): boolean {
    return proto3.util.equals(AnalyticsEventValue, a, b);
  }
}

/**
 * @generated from message plugnmeet.AnalyticsEventData
 */
export class AnalyticsEventData extends Message<AnalyticsEventData> {
  /**
   * @generated from field: string name = 1;
   */
  name = '';

  /**
   * @generated from field: uint32 total = 2;
   */
  total = 0;

  /**
   * @generated from field: repeated plugnmeet.AnalyticsEventValue values = 3;
   */
  values: AnalyticsEventValue[] = [];

  constructor(data?: PartialMessage<AnalyticsEventData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'plugnmeet.AnalyticsEventData';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'name', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'total', kind: 'scalar', T: 13 /* ScalarType.UINT32 */ },
    {
      no: 3,
      name: 'values',
      kind: 'message',
      T: AnalyticsEventValue,
      repeated: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): AnalyticsEventData {
    return new AnalyticsEventData().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsEventData {
    return new AnalyticsEventData().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsEventData {
    return new AnalyticsEventData().fromJsonString(jsonString, options);
  }

  static equals(
    a: AnalyticsEventData | PlainMessage<AnalyticsEventData> | undefined,
    b: AnalyticsEventData | PlainMessage<AnalyticsEventData> | undefined,
  ): boolean {
    return proto3.util.equals(AnalyticsEventData, a, b);
  }
}

/**
 * @generated from message plugnmeet.AnalyticsRoomInfo
 */
export class AnalyticsRoomInfo extends Message<AnalyticsRoomInfo> {
  /**
   * @generated from field: string room_id = 1;
   */
  roomId = '';

  /**
   * @generated from field: string room_title = 2;
   */
  roomTitle = '';

  /**
   * @generated from field: int64 room_total_users = 3;
   */
  roomTotalUsers = protoInt64.zero;

  /**
   * @generated from field: int64 room_creation = 4;
   */
  roomCreation = protoInt64.zero;

  /**
   * @generated from field: int64 room_ended = 5;
   */
  roomEnded = protoInt64.zero;

  /**
   * @generated from field: int64 room_duration = 6;
   */
  roomDuration = protoInt64.zero;

  /**
   * @generated from field: bool enabled_e2ee = 7;
   */
  enabledE2ee = false;

  /**
   * @generated from field: repeated plugnmeet.AnalyticsEventData events = 9;
   */
  events: AnalyticsEventData[] = [];

  constructor(data?: PartialMessage<AnalyticsRoomInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'plugnmeet.AnalyticsRoomInfo';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'room_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'room_title', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    {
      no: 3,
      name: 'room_total_users',
      kind: 'scalar',
      T: 3 /* ScalarType.INT64 */,
    },
    {
      no: 4,
      name: 'room_creation',
      kind: 'scalar',
      T: 3 /* ScalarType.INT64 */,
    },
    { no: 5, name: 'room_ended', kind: 'scalar', T: 3 /* ScalarType.INT64 */ },
    {
      no: 6,
      name: 'room_duration',
      kind: 'scalar',
      T: 3 /* ScalarType.INT64 */,
    },
    { no: 7, name: 'enabled_e2ee', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
    {
      no: 9,
      name: 'events',
      kind: 'message',
      T: AnalyticsEventData,
      repeated: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): AnalyticsRoomInfo {
    return new AnalyticsRoomInfo().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsRoomInfo {
    return new AnalyticsRoomInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsRoomInfo {
    return new AnalyticsRoomInfo().fromJsonString(jsonString, options);
  }

  static equals(
    a: AnalyticsRoomInfo | PlainMessage<AnalyticsRoomInfo> | undefined,
    b: AnalyticsRoomInfo | PlainMessage<AnalyticsRoomInfo> | undefined,
  ): boolean {
    return proto3.util.equals(AnalyticsRoomInfo, a, b);
  }
}

/**
 * @generated from message plugnmeet.AnalyticsUserInfo
 */
export class AnalyticsUserInfo extends Message<AnalyticsUserInfo> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = '';

  /**
   * @generated from field: string name = 2;
   */
  name = '';

  /**
   * @generated from field: bool is_admin = 3;
   */
  isAdmin = false;

  /**
   * @generated from field: optional string extra_data = 4;
   */
  extraData?: string;

  /**
   * @generated from field: repeated plugnmeet.AnalyticsEventData events = 5;
   */
  events: AnalyticsEventData[] = [];

  constructor(data?: PartialMessage<AnalyticsUserInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'plugnmeet.AnalyticsUserInfo';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'user_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'name', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'is_admin', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
    {
      no: 4,
      name: 'extra_data',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 5,
      name: 'events',
      kind: 'message',
      T: AnalyticsEventData,
      repeated: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): AnalyticsUserInfo {
    return new AnalyticsUserInfo().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsUserInfo {
    return new AnalyticsUserInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsUserInfo {
    return new AnalyticsUserInfo().fromJsonString(jsonString, options);
  }

  static equals(
    a: AnalyticsUserInfo | PlainMessage<AnalyticsUserInfo> | undefined,
    b: AnalyticsUserInfo | PlainMessage<AnalyticsUserInfo> | undefined,
  ): boolean {
    return proto3.util.equals(AnalyticsUserInfo, a, b);
  }
}

/**
 * @generated from message plugnmeet.AnalyticsResult
 */
export class AnalyticsResult extends Message<AnalyticsResult> {
  /**
   * @generated from field: plugnmeet.AnalyticsRoomInfo room = 1;
   */
  room?: AnalyticsRoomInfo;

  /**
   * @generated from field: repeated plugnmeet.AnalyticsUserInfo users = 2;
   */
  users: AnalyticsUserInfo[] = [];

  constructor(data?: PartialMessage<AnalyticsResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'plugnmeet.AnalyticsResult';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'room', kind: 'message', T: AnalyticsRoomInfo },
    {
      no: 2,
      name: 'users',
      kind: 'message',
      T: AnalyticsUserInfo,
      repeated: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): AnalyticsResult {
    return new AnalyticsResult().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsResult {
    return new AnalyticsResult().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsResult {
    return new AnalyticsResult().fromJsonString(jsonString, options);
  }

  static equals(
    a: AnalyticsResult | PlainMessage<AnalyticsResult> | undefined,
    b: AnalyticsResult | PlainMessage<AnalyticsResult> | undefined,
  ): boolean {
    return proto3.util.equals(AnalyticsResult, a, b);
  }
}

/**
 * @generated from message plugnmeet.AnalyticsRedisUserInfo
 */
export class AnalyticsRedisUserInfo extends Message<AnalyticsRedisUserInfo> {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string;

  /**
   * @generated from field: bool is_admin = 2;
   */
  isAdmin = false;

  /**
   * @generated from field: optional string extra_data = 3;
   */
  extraData?: string;

  constructor(data?: PartialMessage<AnalyticsRedisUserInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'plugnmeet.AnalyticsRedisUserInfo';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: 'name',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    { no: 2, name: 'is_admin', kind: 'scalar', T: 8 /* ScalarType.BOOL */ },
    {
      no: 3,
      name: 'extra_data',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): AnalyticsRedisUserInfo {
    return new AnalyticsRedisUserInfo().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsRedisUserInfo {
    return new AnalyticsRedisUserInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): AnalyticsRedisUserInfo {
    return new AnalyticsRedisUserInfo().fromJsonString(jsonString, options);
  }

  static equals(
    a:
      | AnalyticsRedisUserInfo
      | PlainMessage<AnalyticsRedisUserInfo>
      | undefined,
    b:
      | AnalyticsRedisUserInfo
      | PlainMessage<AnalyticsRedisUserInfo>
      | undefined,
  ): boolean {
    return proto3.util.equals(AnalyticsRedisUserInfo, a, b);
  }
}
