// @generated by protoc-gen-es v0.0.10 with parameter "target=js+dts"
// @generated from file plugnmeet_common_api.proto (package plugnmeet, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";
import {DataMsgBodyType} from "./plugnmeet_datamessage_pb.js";

/**
 * @generated from enum plugnmeet.SwitchPresenterTask
 */
export const SwitchPresenterTask = proto3.makeEnum(
  "plugnmeet.SwitchPresenterTask",
  [
    {no: 0, name: "PROMOTE"},
    {no: 1, name: "DEMOTE"},
  ],
);

/**
 * @generated from enum plugnmeet.ExternalMediaPlayerTask
 */
export const ExternalMediaPlayerTask = proto3.makeEnum(
  "plugnmeet.ExternalMediaPlayerTask",
  [
    {no: 0, name: "START_PLAYBACK"},
    {no: 1, name: "END_PLAYBACK"},
  ],
);

/**
 * @generated from enum plugnmeet.ExternalDisplayLinkTask
 */
export const ExternalDisplayLinkTask = proto3.makeEnum(
  "plugnmeet.ExternalDisplayLinkTask",
  [
    {no: 0, name: "START_EXTERNAL_LINK"},
    {no: 1, name: "STOP_EXTERNAL_LINK"},
  ],
);

/**
 * @generated from message plugnmeet.CommonResponse
 */
export const CommonResponse = proto3.makeMessageType(
  "plugnmeet.CommonResponse",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.VerifyTokenReq
 */
export const VerifyTokenReq = proto3.makeMessageType(
  "plugnmeet.VerifyTokenReq",
  () => [
    { no: 1, name: "is_production", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
);

/**
 * @generated from message plugnmeet.VerifyTokenRes
 */
export const VerifyTokenRes = proto3.makeMessageType(
  "plugnmeet.VerifyTokenRes",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "livekit_host", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message plugnmeet.MuteUnMuteTrackReq
 */
export const MuteUnMuteTrackReq = proto3.makeMessageType(
  "plugnmeet.MuteUnMuteTrackReq",
  () => [
    { no: 1, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "muted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "Requested_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.RemoveParticipantReq
 */
export const RemoveParticipantReq = proto3.makeMessageType(
  "plugnmeet.RemoveParticipantReq",
  () => [
    { no: 1, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "block_user", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message plugnmeet.DataMessageReq
 */
export const DataMessageReq = proto3.makeMessageType(
  "plugnmeet.DataMessageReq",
  () => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "room_sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "user_sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "msg_body_type", kind: "enum", T: proto3.getEnumType(DataMsgBodyType) },
    { no: 6, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "Requested_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "send_to", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 9, name: "is_admin", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message plugnmeet.RoomEndAPIReq
 */
export const RoomEndAPIReq = proto3.makeMessageType(
  "plugnmeet.RoomEndAPIReq",
  () => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.ChangeVisibilityRes
 */
export const ChangeVisibilityRes = proto3.makeMessageType(
  "plugnmeet.ChangeVisibilityRes",
  () => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "visible_notepad", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "visible_white_board", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
);

/**
 * @generated from message plugnmeet.SwitchPresenterReq
 */
export const SwitchPresenterReq = proto3.makeMessageType(
  "plugnmeet.SwitchPresenterReq",
  () => [
    { no: 1, name: "task", kind: "enum", T: proto3.getEnumType(SwitchPresenterTask) },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Requested_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.ExternalMediaPlayerReq
 */
export const ExternalMediaPlayerReq = proto3.makeMessageType(
  "plugnmeet.ExternalMediaPlayerReq",
  () => [
    { no: 1, name: "task", kind: "enum", T: proto3.getEnumType(ExternalMediaPlayerTask) },
    { no: 2, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "seek_to", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 4, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.ExternalDisplayLinkReq
 */
export const ExternalDisplayLinkReq = proto3.makeMessageType(
  "plugnmeet.ExternalDisplayLinkReq",
  () => [
    { no: 1, name: "task", kind: "enum", T: proto3.getEnumType(ExternalDisplayLinkTask) },
    { no: 2, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.CreateEtherpadSessionRes
 */
export const CreateEtherpadSessionRes = proto3.makeMessageType(
  "plugnmeet.CreateEtherpadSessionRes",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pad_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "readonly_pad_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message plugnmeet.CleanEtherpadReq
 */
export const CleanEtherpadReq = proto3.makeMessageType(
  "plugnmeet.CleanEtherpadReq",
  () => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "node_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pad_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.ChangeEtherpadStatusReq
 */
export const ChangeEtherpadStatusReq = proto3.makeMessageType(
  "plugnmeet.ChangeEtherpadStatusReq",
  () => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "is_active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

