// @generated by protoc-gen-es v0.1.0 with parameter "target=js+dts"
// @generated from file plugnmeet_breakout_room.proto (package plugnmeet, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message plugnmeet.CreateBreakoutRoomsReq
 */
export const CreateBreakoutRoomsReq = proto3.makeMessageType(
  "plugnmeet.CreateBreakoutRoomsReq",
  () => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "requested_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "duration", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "welcome_msg", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "rooms", kind: "message", T: BreakoutRoom, repeated: true },
  ],
);

/**
 * @generated from message plugnmeet.BreakoutRoom
 */
export const BreakoutRoom = proto3.makeMessageType(
  "plugnmeet.BreakoutRoom",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "duration", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "started", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "created", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "users", kind: "message", T: BreakoutRoomUser, repeated: true },
  ],
);

/**
 * @generated from message plugnmeet.BreakoutRoomUser
 */
export const BreakoutRoomUser = proto3.makeMessageType(
  "plugnmeet.BreakoutRoomUser",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "joined", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message plugnmeet.IncreaseBreakoutRoomDurationReq
 */
export const IncreaseBreakoutRoomDurationReq = proto3.makeMessageType(
  "plugnmeet.IncreaseBreakoutRoomDurationReq",
  () => [
    { no: 1, name: "breakout_room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "duration", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.BroadcastBreakoutRoomMsgReq
 */
export const BroadcastBreakoutRoomMsgReq = proto3.makeMessageType(
  "plugnmeet.BroadcastBreakoutRoomMsgReq",
  () => [
    { no: 1, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.JoinBreakoutRoomReq
 */
export const JoinBreakoutRoomReq = proto3.makeMessageType(
  "plugnmeet.JoinBreakoutRoomReq",
  () => [
    { no: 1, name: "breakout_room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "is_admin", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message plugnmeet.EndBreakoutRoomReq
 */
export const EndBreakoutRoomReq = proto3.makeMessageType(
  "plugnmeet.EndBreakoutRoomReq",
  () => [
    { no: 1, name: "breakout_room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message plugnmeet.BreakoutRoomRes
 */
export const BreakoutRoomRes = proto3.makeMessageType(
  "plugnmeet.BreakoutRoomRes",
  () => [
    { no: 1, name: "status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "room", kind: "message", T: BreakoutRoom, opt: true },
    { no: 5, name: "rooms", kind: "message", T: BreakoutRoom, repeated: true },
  ],
);

