// @generated by protoc-gen-es v0.3.0 with parameter "target=js+dts"
// @generated from file plugnmeet_recording.proto (package plugnmeet, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { RecordingTasks } from "./plugnmeet_recorder_pb.js";

/**
 * @generated from message plugnmeet.RecordingReq
 */
export const RecordingReq = proto3.makeMessageType(
  "plugnmeet.RecordingReq",
  () => [
    { no: 1, name: "task", kind: "enum", T: proto3.getEnumType(RecordingTasks) },
    { no: 2, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "rtmp_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "custom_design", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

