name: Nightly build to test
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.MYNA_APP_ID }}
          private-key: ${{ secrets.MYNA_APP_SECRET }}
      - name: 'bot: version bump'
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          version-type: 'prerelease'
          commit-message: 'bump version'
          skip-tag: 'true'
          skip-commit: 'false'
      - name: Build project
        run: |
          pnpm install
          pnpm run build
          timestamp=$(date +%s)
          echo "dev-${timestamp}" > dist/version.txt
          mkdir -p tmp/client
          rsync -ar LICENSE dist tmp/client/
          cd tmp
          zip -X -r client.zip client
      - name: Upload by ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PNM_FTP_HOST }}
          username: ${{ secrets.PNM_FTP_USER }}
          password: ${{ secrets.PNM_FTP_PASSWORD }}
          local-dir: "./tmp/"
          state-name: ".client-sync-state.json"
          exclude: |
            **/client/**
